# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' return the number of fastq entries previously parsed from provided Fastq file
#'
#' @return long integer of read fastq elements
#' @export
getFastqCount <- function() {
    .Call(`_nanopoRe_getFastqCount`)
}

#' return the number of fastq bases previously parsed from provided Fastq file
#'
#' @return long long integer of read fastq bases
#' @export
getFastqBases <- function() {
    .Call(`_nanopoRe_getFastqBases`)
}

#' count of fastq elements rejected due to malformed fastq header
#'
#' @return integer count of malformed fastq header entries
#' @export
getMalformedFastqHeaderCount <- function() {
    .Call(`_nanopoRe_getMalformedFastqHeaderCount`)
}

#' count of fastq elements rejected due to line 3 plus separator
#'
#' @return integer count of malformed fastq '+' separator entries
#' @export
getFastqPlusErrorCount <- function() {
    .Call(`_nanopoRe_getFastqPlusErrorCount`)
}

#' count of fastq elements rejected due to zero length sequence
#'
#' @return integer count of fastq entries with zero sequence length
#' @export
getZeroLengthSequenceCount <- function() {
    .Call(`_nanopoRe_getZeroLengthSequenceCount`)
}

#' count of fastq elements rejected due to mismatch between sequence and quality field lengths
#'
#' @return integer count of fastq entries with seq/qual length challenges
#' @export
getSequenceQualityMismatchCount <- function() {
    .Call(`_nanopoRe_getSequenceQualityMismatchCount`)
}

#' count of lines of fastq file skipped to enable fastq entry parsing
#'
#' @return integer count of lines skipped
#' @export
getSkippedLineCount <- function() {
    .Call(`_nanopoRe_getSkippedLineCount`)
}

#' parse a fastq file aiming to validate sequences
#'
#' @param x A fastq format DNA/RNA sequence file
#' @export
fastqValidator <- function(fastq) {
    .Call(`_nanopoRe_fastqValidator`, fastq)
}

#' Multiply a number by two
#'
#' @param x A single integer.
#' @export
timesTwo <- function(x) {
    .Call(`_nanopoRe_timesTwo`, x)
}

